In [ ]:
!pip install langchain
!pip install tiktoken
!pip install -U langchain langchain-community
!pip install -U langchain langchain-core langchain-openai
!pip install chromadb
!pip install -U langchain sentence-transformers chromadb
!pip install -U sentence-transformers langchain

In [ ]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import os
os.environ['OPENAI_API_KEY'] = ''

# Data Loader
 - WebBaseLoader
 - TextLoader
 - DierctoryLoader
 - CSVLoader
 - PDFLoader

In [ ]:
# WebBaseLoader

import bs4
from langchain_community.document_loaders import WebBaseLoader

url_one = "https://blog.langchain.dev/customers-replit/"
url_two = "https://blog.langchain.dev/langgraph-v0-2/"

loader = WebBaseLoader(
    web_paths=(url_one, url_two),
    bs_kwargs=dict(
        parse_only=bs4.SoupStrainer(
            class_=("article-header", "article-content")
            )
      )
    )

docs = loader.load()
docs[0]

In [ ]:
#TextLoader

from langchain_community.document_loaders import TextLoader

loader = TextLoader("/content/drive/MyDrive/Colab Notebooks/history.txt")
data = loader.load()

print(type(data))
print(len(data))
print(data[0].page_content)

<class 'list'>
1
한국의 역사는 수천 년에 걸쳐 이어져 온 긴 여정 속에서 다양한 문화와 전통이 형성되고 발전해 왔습니다. 고조선에서 시작해 삼국 시대의 경쟁, 그리고 통일 신라와 고려를 거쳐 조선까지, 한반도는 많은 변화를 겪었습니다.

고조선은 기원전 2333년 단군왕검에 의해 세워졌다고 전해집니다. 이는 한국 역사상 최초의 국가로, 한민족의 시원이라 할 수 있습니다. 이후 기원전 1세기경에는 한반도와 만주 일대에서 여러 소국이 성장하며 삼한 시대로 접어듭니다.

4세기경, 고구려, 백제, 신라의 삼국이 한반도의 주요 세력으로 부상했습니다. 이 시기는 삼국이 각각 문화와 기술, 무력을 발전시키며 경쟁적으로 성장한 시기로, 한국 역사에서 중요한 전환점을 마련했습니다. 특히 고구려는 북방의 강대국으로 성장하여 중국과도 여러 차례 전쟁을 벌였습니다.

7세기 말, 신라는 당나라와 연합하여 백제와 고구려를 차례로 정복하고, 한반도 최초의 통일 국가인 통일 신라를 건립합니다. 이 시기에 신라는 불교를 국교로 채택하며 문화와 예술이 크게 발전했습니다.

그러나 10세기에 이르러 신라는 내부의 분열과 외부의 압력으로 쇠퇴하고, 이를 대체하여 고려가 성립됩니다. 고려 시대에는 과거제도의 도입과 더불어 청자 등 고려 고유의 문화가 꽃피었습니다.

조선은 1392년 이성계에 의해 건국되어, 1910년까지 이어졌습니다. 조선 초기에는 세종대왕이 한글을 창제하여 백성들의 문해율을 높이는 등 문화적, 과학적 성취가 이루어졌습니다. 그러나 조선 후기에는 내부적으로 실학의 발전과 함께 사회적 변화가 모색되었으나, 외부로부터의 압력은 점차 커져만 갔습니다.

19세기 말부터 20세기 초에 걸쳐 한국은 제국주의 열강의 침략을 받으며 많은 시련을 겪었습니다. 1910년, 한국은 일본에 의해 강제로 병합되어 35년간의 식민 지배를 받게 됩니다. 이 기간 동안 한국인들은 독립을 위한 다양한 운동을 전개했으며, 이는 1945년 일본의 패망으로 이어지는 독립으로 결실을 맺었습니다.

해방 후 한반도는 남북으로 분단되어 각각 다른 정부가 수립되었고, 1950년에는 한국전쟁이 발발하여 큰 피해를 입었습니다. 전쟁 후 남한은 빠른 경제 발전을 이루며 오늘날에 이르렀습니다.

한국의 역사는 오랜 시간 동안 수많은 시련과 도전을 겪으며 형성된 깊은 유산을 지니고 있습니다. 오늘날 한국은 그 역사적 배경 위에서 세계적으로 중요한 역할을 하고 있으며, 과거의 역사가 현재와 미래에 어떻게 영향을 미치는지를 이해하는 것은 매우 중요합니다.

In [ ]:
!pip install unstructured

In [ ]:
# DierctoryLoader
import os
from glob import glob
files = glob(os.path.join("/content/drive/MyDrive/Colab Notebooks/", "*.txt"))

In [ ]:
files

['/content/drive/MyDrive/Colab Notebooks/history.txt']

In [ ]:
# CSVLoader
from langchain_community.document_loaders.csv_loader import CSVLoader

loader = CSVLoader(file_path = '/content/drive/MyDrive/Colab Notebooks/한국주택금융공사_주택금융관련_지수_20160101.csv', encoding='cp949')
data = loader.load()

len(data)
print(data[0].page_content)

연도: 2004-01-01
전국소득대비 주택가격 비율: 4.21
서울소득대비 주택가격 비율: 4.89
부산소득대비 주택가격 비율: 3.95
대구소득대비 주택가격 비율: 3.73
인천소득대비 주택가격 비율: 4.65
광주소득대비 주택가격 비율: 2.81
대전소득대비 주택가격 비율: 4.68
울산소득대비 주택가격 비율: 2.66
세종소득대비 주택가격 비율: 0
경기소득대비 주택가격 비율: 4.17
강원소득대비 주택가격 비율: 2.49
충북소득대비 주택가격 비율: 2.62
충남소득대비 주택가격 비율: 2.17
전북소득대비 주택가격 비율: 3.12
전남소득대비 주택가격 비율: 2.12
경북소득대비 주택가격 비율: 2.12
경남소득대비 주택가격 비율: 3.81
제주소득대비 주택가격 비율: 2.99
전국평균 대출금액  평균 연소득: 2.36
서울평균 대출금액  평균 연소득: 2.61
부산평균 대출금액  평균 연소득: 2.35
대구평균 대출금액  평균 연소득: 2.24
인천평균 대출금액  평균 연소득: 2.7
광주평균 대출금액  평균 연소득: 1.6
대전평균 대출금액  평균 연소득: 2.26
울산평균 대출금액  평균 연소득: 1.67
세종평균 대출금액  평균 연소득: 0
경기평균 대출금액  평균 연소득: 2.42
강원평균 대출금액  평균 연소득: 1.44
충북평균 대출금액  평균 연소득: 1.53
충남평균 대출금액  평균 연소득: 1.21
전북평균 대출금액  평균 연소득: 1.9
전남평균 대출금액  평균 연소득: 1.42
경북평균 대출금액  평균 연소득: 1.31
경남평균 대출금액  평균 연소득: 2.06
제주평균 대출금액  평균 연소득: 1.28